"""Canonical modifier projections, target validation, and selection."""

from .contracts import (
    CANONICAL_MODIFIER_REQUIRED_COLUMNS,
    CANONICAL_MODIFIER_VALUE_COLUMNS,
    ModifierColumn,
    ModifierIdentity,
    ModifierRow,
    ModifierSelectionPolicy,
    ModifierSelectionSpec,
    ModifierTargetDiagnostic,
    ModifierTargetDiagnosticCode,
    ModifierTargetDiagnosticColumn,
    ModifierTargetIdentity,
    ValuedModifierRow,
)
from .metadata import (
    MODIFIER_SOURCE_MODEL_SPECS_BY_TABLE,
    MODIFIER_TARGET_SPECS_BY_TABLE,
    SUPPORTED_MODIFIER_MODELS,
    ModifierSourceModelSpec,
    ModifierTargetModelSpec,
    UnsupportedModifierSourceModelError,
    UnsupportedModifierTargetError,
    modifier_source_model_spec,
    modifier_target_model_spec,
)
from .projections import (
    canonical_modifier_projection,
    canonical_modifier_union,
)
from .selection import (
    MODIFIER_RANK,
    InvalidModifierSourceError,
    modifier_order_expressions,
    modifier_row_number,
    ranked_modifier_select,
    selected_modifier_select,
)
from .targets import (
    RESOLVED_TARGET_EVENT_ID,
    RESOLVED_TARGET_FIELD_CONCEPT_ID,
    RESOLVED_TARGET_PERSON_ID,
    RESOLVED_TARGET_SOURCE_TABLE,
    InvalidModifierTargetSourceError,
    ModifierTargetQueries,
    canonical_modifier_target_projection,
    modifier_target_queries,
)

__all__ = [
    "CANONICAL_MODIFIER_REQUIRED_COLUMNS",
    "CANONICAL_MODIFIER_VALUE_COLUMNS",
    "MODIFIER_SOURCE_MODEL_SPECS_BY_TABLE",
    "MODIFIER_RANK",
    "MODIFIER_TARGET_SPECS_BY_TABLE",
    "RESOLVED_TARGET_EVENT_ID",
    "RESOLVED_TARGET_FIELD_CONCEPT_ID",
    "RESOLVED_TARGET_PERSON_ID",
    "RESOLVED_TARGET_SOURCE_TABLE",
    "SUPPORTED_MODIFIER_MODELS",
    "InvalidModifierSourceError",
    "InvalidModifierTargetSourceError",
    "ModifierColumn",
    "ModifierIdentity",
    "ModifierSourceModelSpec",
    "ModifierRow",
    "ModifierSelectionPolicy",
    "ModifierSelectionSpec",
    "ModifierTargetDiagnostic",
    "ModifierTargetDiagnosticCode",
    "ModifierTargetDiagnosticColumn",
    "ModifierTargetIdentity",
    "ModifierTargetModelSpec",
    "ModifierTargetQueries",
    "UnsupportedModifierSourceModelError",
    "UnsupportedModifierTargetError",
    "ValuedModifierRow",
    "canonical_modifier_projection",
    "canonical_modifier_target_projection",
    "canonical_modifier_union",
    "modifier_order_expressions",
    "modifier_row_number",
    "modifier_source_model_spec",
    "modifier_target_model_spec",
    "modifier_target_queries",
    "ranked_modifier_select",
    "selected_modifier_select",
]
